Signs repository and endpoint
ElectronicBabylonianLiterature/ebl-api pull request #105
Opened 2021-04-07 22:30 UTC by yCobanoglu

2021-04-07 22:30 UTC, yCobanoglu commented
![](https://github.trello.services/images/mini-trello-icon.png) [Search for signs interface](https://trello.com/c/wDJwbcrk/514-search-for-signs-interface)

2021-04-27 09:40 UTC, jlaasonen requested changes
You created a package for signs. The existing modules for signs should be moved there.

2021-04-27 09:40 UTC, jlaasonen commented on ebl/tests/transliteration/test_memoizing_sign_repository.py
> +    [memoizing_sign_repository.create(sign) for sign in signs]
Why use list comprehension when you are not using the list?

Is it necessary to create all the signs to test the memoization?

2021-04-27 09:40 UTC, jlaasonen commented on ebl/tests/transliteration/test_sign_repository.py
> +
The schema tests should go to own module.

2021-04-27 09:40 UTC, jlaasonen commented on ebl/tests/transliteration/test_sign_repository.py
> +    assert sign_repository.search_all("none", 1) == []
Add separate test cases for different inputs.

2021-04-27 09:40 UTC, jlaasonen commented on ebl/tests/transliteration/test_sign_repository.py
> +    assert sign_repository.search_by_id("none") == []
Add separate test cases for different inputs.

2021-04-27 09:40 UTC, jlaasonen commented on ebl/tests/transliteration/test_sign_repository.py
> +    assert sign_repository.search_composite_signs("ši", 1) == [sign_igi]
These tests only test the stubs, not the actual implementation.

2021-04-27 09:40 UTC, jlaasonen commented on ebl/tests/signs/test_signs_route.py
> +
Invalid inputs should also be tested.

2021-04-27 09:40 UTC, jlaasonen commented on ebl/transliteration/domain/sign.py
> +    mes_zl: Optional[str] = None
Is there a difference between `""` and `None`? If not, using `missing` in the schema would remove the need for null checks.

2021-04-29 11:29 UTC, yCobanoglu commented on ebl/signs/web/sign_search.py
> +        return params
i made a copy and return that copy now.

2021-04-30 06:32 UTC, jlaasonen approved these changes

2021-05-17 09:20 UTC, merged