retrieve annotations images and ground truth
ElectronicBabylonianLiterature/ebl-api pull request #129
Opened 2021-08-10 10:31 UTC by yCobanoglu

2021-08-16 12:23 UTC, jlaasonen commented
@yCobanoglu why so low test coverage?

2021-08-17 06:38 UTC, jlaasonen commented on ebl/fragmentarium/retrieve_annotations.py
> +    Some images are in our database, some aren't so we have to retrieve them from CDLI.
Which images are not in our database? The annotations are loaded from our database, so the images should be there.

2021-08-17 13:40 UTC, jlaasonen requested changes

2021-08-17 13:40 UTC, jlaasonen commented on ebl/fragmentarium/retrieve_annotations.py
> +    which aren't complete.
This redundant you can e.g extract method `filter_incomplete_annotations`.

2021-08-17 13:40 UTC, jlaasonen commented on ebl/fragmentarium/retrieve_annotations.py
> +    Output 0,0 is top left
If you use a class you can name properties accordingly. E.g.

```
box.top_left.x
box.icdar_coordinates
```

To make this apparent from the code.

2021-08-17 13:40 UTC, jlaasonen commented on ebl/fragmentarium/retrieve_annotations.py
> +        new_height = int(round(bbox.geometry.height / 100 * y_size))
It feels like this could be part of `calculate_bbox_coordinates`.

2021-08-21 09:04 UTC, yCobanoglu commented on ebl/fragmentarium/retrieve_annotations.py
> +    Some images are in our database, some aren't so we have to retrieve them from CDLI.
If it's not in CDLI it is throwing an error. User can inspect it manually then.

2021-08-24 07:58 UTC, jlaasonen requested changes

2021-08-24 07:58 UTC, jlaasonen commented on ebl/fragmentarium/retrieve_annotations.py
> +    """
The comment is out of place. Seems to be related to `from_geometry`.

2021-08-24 07:58 UTC, jlaasonen commented on ebl/fragmentarium/retrieve_annotations.py
> +        return BBox.from_rectange(new_x, new_y, new_width, new_height)
The variables names could be improved to reduce the need for comments.

E.g. `image_width, image_height, absolute_x, absolute_y, absolute_width, absolute_height`.

2021-08-24 07:58 UTC, jlaasonen commented on ebl/fragmentarium/retrieve_annotations.py
> +class BBox:
Use descriptive names instead of cryptic abbreviations.

2021-08-24 07:58 UTC, jlaasonen commented on ebl/tests/fragmentarium/test_retrieve_annotations.py
> +    when(retrieve_annotations).write_annotations(...).thenReturn(None)
This is a strange mix of integration and unit test. Fragments and annotations come from the DB, but the photo repository is mocked. 

Either put the photo to DB too or mock all the repositories.

If you want to do a proper integration test, use temporary directories to test the files. See [How to use temporary directories and files in tests](https://docs.pytest.org/en/latest/how-to/tmp_path.html)

When using the mocks test that correct arguments are passed.

2021-09-03 22:19 UTC, yCobanoglu commented
@jlaasonen i resolved all comments and merged with migrate_annotations. I will now create the request in that branch. So everything will be now in [https://github.com/ElectronicBabylonianLiterature/ebl-api/pull/136](https://github.com/ElectronicBabylonianLiterature/ebl-api/pull/136).

2021-09-03 22:19 UTC, closed without merging