add enum
ElectronicBabylonianLiterature/ebl-api pull request #160
Opened 2021-11-03 12:53 UTC by yCobanoglu

2021-11-03 15:02 UTC, jlaasonen requested changes

2021-11-03 15:02 UTC, jlaasonen commented on ebl/fragmentarium/domain/annotation.py
> +    PARTIALLYBROKEN = "PartiallyBroken"
Separate words with an underscore.

2021-11-03 15:02 UTC, jlaasonen commented on ebl/fragmentarium/domain/annotation.py
> +    PARTIALLYBROKEN = "PartiallyBroken"
https://www.python.org/dev/peps/pep-0008/#constants

2021-11-04 17:15 UTC, yCobanoglu commented on ebl/fragmentarium/domain/annotation.py
> +    PARTIALLYBROKEN = "PartiallyBroken"
ok.

2021-11-05 06:59 UTC, jlaasonen approved these changes

2021-11-05 18:07 UTC, merged