Signs images
ElectronicBabylonianLiterature/ebl-api pull request #172
Opened 2021-11-30 20:27 UTC by yCobanoglu

2022-01-03 17:41 UTC, yCobanoglu commented
![](https://github.trello.services/images/mini-trello-icon.png) [Display annotations in Signs interface](https://trello.com/c/C3BG2qRF/538-display-annotations-in-signs-interface)

2022-01-11 07:45 UTC, jlaasonen requested changes

2022-01-11 07:45 UTC, jlaasonen commented on ebl/fragmentarium/application/annotations_image_extractor.py
> +            return label, lines
This should be fixed. You could use e.g. single dispatch.

2022-01-11 07:45 UTC, jlaasonen commented on ebl/fragmentarium/application/annotations_image_extractor.py
> +    def _calculate_label(total: Tuple[LineLabel, Sequence[Line]], line: Line):
The return type is missing.

2022-01-11 07:45 UTC, jlaasonen commented on ebl/fragmentarium/application/annotations_image_extractor.py
> +    ):
The return type is missing.

2022-01-11 07:45 UTC, jlaasonen commented on ebl/tests/conftest.py
> +        return self._file.getvalue()
Does this work if the size is not -1?

2022-01-11 07:45 UTC, jlaasonen commented on ebl/tests/fragmentarium/test_annotations_image_extractor.py
> +    assert first_cropped_annotation.label != "i stone wig i 8'"
What is the purpose of this assertion?
Wouldnt it be better to test that the label is correct?

2022-01-11 07:45 UTC, jlaasonen commented on ebl/tests/fragmentarium/test_annotations_repository.py
> +            assert annotation.data.sign_name == sign_query
The test is incomplete. It would not catch e.g. spurious annotations or incorrect values of other properties.

2022-01-11 07:45 UTC, jlaasonen commented on ebl/tests/signs/test_sign_images_route.py
> +    assert isinstance(result_json["label"], str)
Why do you only test the result partially?

2022-01-11 07:45 UTC, jlaasonen commented on ebl/tests/transliteration/test_line_label.py
> +def test_line_label(line_label, expected):
The test name is misleading. You are only testing abbreviation property.

2022-01-11 07:45 UTC, jlaasonen commented on ebl/transliteration/domain/line_label.py
> +    def is_line_number(self, line_number_to_match: int) -> bool:
The name is confusing as it does not check if something is a line number. `has_line_number` might be better.

What is the purpose of this method? It ignores prime, prefix and suffix and an index from the annotation path is passed in.  https://github.com/ElectronicBabylonianLiterature/ebl-api/blob/b6889aaa72f47eb7216e8f5649f487792674445d/ebl/fragmentarium/application/annotations_image_extractor.py#L96)

2022-01-11 07:45 UTC, jlaasonen commented on ebl/transliteration/domain/line_label.py
> +    def is_line_number(self, line_number_to_match: int) -> bool:
This should be fixed.

2022-01-11 10:32 UTC, jlaasonen commented on ebl/fragmentarium/application/annotations_image_extractor.py
> +    def _calculate_label(total: Tuple[LineLabel, Sequence[Line]], line: Line):
The missing type hides problems with the implementation. The method is used with `reduce` which means that the type of the accumulator and return value should be the same. That is not the case in line 47 which returns `Tuple[LineLabel, Sequence[Union[Line, List[Union[LineLabel, Line]]]`.

2022-01-11 10:35 UTC, jlaasonen commented on ebl/fragmentarium/application/annotations_image_extractor.py
> +    def _calculate_label(total: Tuple[LineLabel, Sequence[Line]], line: Line):
The logic is mostly duplicated from https://github.com/ElectronicBabylonianLiterature/ebl-api/blob/bf802db8b789979875856abafdd950ae41b93c5b/ebl/transliteration/domain/text.py#L105

The code should be changed so that there is no duplicate logic.

2022-01-12 13:56 UTC, yCobanoglu commented on ebl/fragmentarium/application/annotations_image_extractor.py
> +            return label, lines
ok yeah i copied this one to one from javascript i will do single dispatch. Single dispatch needs so much code in python.

2022-01-12 21:42 UTC, yCobanoglu commented on ebl/tests/conftest.py
> +        return self._file.getvalue()
No so i one wants to only read specific number of bytes it won't work. The problem previously was that once read the buffer doesn't reset itself so for proceeding tests `read` returned nothing.  What should i do ?

2022-01-14 22:28 UTC, yCobanoglu commented on ebl/tests/fragmentarium/test_annotations_repository.py
> +            assert annotation.data.sign_name == sign_query
but why would i test anything beyond the sign_name if something was incorrect and should have been prevented way earlier than here or am i missing something ? The method should retrieve every annotation that has that specific sign_name only.

2022-01-17 11:34 UTC, jlaasonen commented on ebl/tests/conftest.py
> +        return self._file.getvalue()
Do not use the same file in multiple tests, if they change its state.

2022-01-17 11:41 UTC, jlaasonen commented on ebl/tests/conftest.py
> +        return self._file.getvalue()
If you return the whole file everytime, callers reading the file in chunks may not work as intended.

2022-01-18 09:12 UTC, jlaasonen requested changes

2022-01-19 13:48 UTC, jlaasonen approved these changes

2022-01-19 19:54 UTC, merged