smart-pager increment pager correctly (according to museumNumber)
ElectronicBabylonianLiterature/ebl-api pull request #181
Opened 2022-01-12 20:54 UTC by yCobanoglu

2022-01-25 08:37 UTC, jlaasonen commented on ebl/fragmentarium/infrastructure/fragment_repository.py
> +    def query_next_and_previous_fragment(
This must be fixed the code is very messy. It is hard to figure out what is going on. The logic appears to be a duplicate of the `MuseumNumber` comparison. If the existing logic cannot be used, the common parts should be extracted.

2022-01-25 08:45 UTC, jlaasonen requested changes

2022-01-25 08:45 UTC, jlaasonen commented on ebl/tests/fragmentarium/test_fragment_repository.py
> +]
There should be test cases with suffixes.

2022-01-25 08:45 UTC, jlaasonen commented on ebl/fragmentarium/infrastructure/fragment_repository.py
> +        }
Use a proper model instead of passing dictionaries around.

2022-01-25 08:50 UTC, jlaasonen commented on ebl/tests/fragmentarium/test_fragment_repository.py
> +]
..and non-numeric number.

2022-01-30 22:42 UTC, yCobanoglu commented on ebl/tests/fragmentarium/test_fragment_repository.py
> +]
"1841-57" is non numeric or isn't that what you meant ?

2022-01-31 12:22 UTC, jlaasonen commented on ebl/tests/fragmentarium/test_fragment_repository.py
> +]
Non-numeric **number**. "1841-57" is a **prefix** in the data above.

E.g "Fragment" in "Test.Fragment"

2022-01-31 12:46 UTC, jlaasonen requested changes
The complexity issues must be fixed. The code is too hard to understand.

2022-02-02 22:51 UTC, yCobanoglu commented
![](https://github.trello.services/images/mini-trello-icon.png) [Use parsed museum number for smart pager](https://trello.com/c/VKmEfqYY/397-use-parsed-museum-number-for-smart-pager)

2022-02-04 08:32 UTC, jlaasonen requested changes

2022-02-04 08:32 UTC, jlaasonen commented on ebl/fragmentarium/infrastructure/fragment_repository.py
> +        comp: Callable[[MuseumNumber, MuseumNumber], bool],
What's a "comp"? Do not unnecessarily truncate words.

2022-02-04 08:32 UTC, jlaasonen commented on ebl/fragmentarium/infrastructure/fragment_repository.py
> +    ):
Add type hints for `cursor` and return value.

Use a descriptive name. There is no list involved.

2022-02-04 08:32 UTC, jlaasonen commented on ebl/fragmentarium/infrastructure/fragment_repository.py
> +        self.query_by_museum_number(museum_number)
What's this for? The fragment is not used.

2022-02-04 08:32 UTC, jlaasonen commented on ebl/fragmentarium/infrastructure/fragment_repository.py
> +        return first, last
`self` is not used. These could be moved out of the class.

The names are misleading. Compare would indicate that the result tells if something is greater/less than or equal.

2022-02-04 11:14 UTC, jlaasonen approved these changes

2022-02-04 11:40 UTC, merged

2022-02-04 11:41 UTC, yCobanoglu commented on ebl/fragmentarium/infrastructure/fragment_repository.py
> +        self.query_by_museum_number(museum_number)
this is used to check if the museum number exists at all