precompute images
ElectronicBabylonianLiterature/ebl-api pull request #207
Opened 2022-03-07 13:46 UTC by yCobanoglu

2022-03-18 12:44 UTC, jlaasonen commented
CPython tests pass but PyPy tests fail. Are there randomly failing tests or compatibility issues?

2022-03-18 13:05 UTC, jlaasonen requested changes
There seem to be spurious changes related to chapter display. Where do they come from?

2022-03-18 13:05 UTC, jlaasonen commented on ebl/fragmentarium/application/cropped_sign_images_repository.py
> +    def create(self, cropped_sign_image: Sequence[CroppedSignImage]) -> None:
Does this create one or many images? Name the method and argument accordingly.

2022-03-18 13:05 UTC, jlaasonen commented on ebl/fragmentarium/infrastructure/cropped_sign_images_repository.py
> +            self._collection.insert_one(schema.dump(element))
MongoDB can insert many. You could add a method to `MongoCollection`.

2022-03-21 13:27 UTC, yCobanoglu commented on ebl/tests/fragmentarium/test_annotations_service.py
> +    when(annotations_repository).create_or_update(...).thenReturn()
some properties (`croppedImage`) are created during the invokation of the tested method they can't be predicted in advance.

2022-03-22 07:44 UTC, jlaasonen commented on ebl/tests/fragmentarium/test_annotations_service.py
> +    when(annotations_repository).create_or_update(...).thenReturn()
How do you know it works if it is unpredictable?

2022-03-22 08:51 UTC, jlaasonen requested changes

2022-03-22 08:51 UTC, jlaasonen commented on ebl/fragmentarium/application/annotations_service.py
> +    def _cropped_image_from_annotations(
This should be fixed. The method is hard to read.

2022-03-22 08:51 UTC, jlaasonen commented on ebl/fragmentarium/application/annotations_service.py
> +            image_id = str(bson.ObjectId())
Use UUIDs for unique identifiers.  Do not let Mongo leak out of `infrastructure`.

2022-03-22 08:51 UTC, jlaasonen commented on ebl/fragmentarium/application/annotations_service.py
> +        )
This could go to `LineLabel`.

2022-03-22 08:51 UTC, jlaasonen commented on ebl/fragmentarium/application/annotations_service.py
> +        return Base64(base64.b64encode(buf.getvalue()).decode("utf-8"))
This could go to `Annotation`.

2022-03-22 08:51 UTC, jlaasonen commented on ebl/fragmentarium/application/annotations_service.py
> +        return line_number.start.number <= number <= line_number.end.number
These could go to line number models.

2022-03-22 08:51 UTC, jlaasonen commented on ebl/fragmentarium/application/annotations_service.py
> +        )[0]
Would be nicer to have a `from_annotation` factory method or `bounding_box` getter in `Annotation`.

2022-03-22 08:51 UTC, jlaasonen commented on ebl/tests/fragmentarium/test_annotations_service.py
> +    when(annotations_repository).create_or_update(...).thenReturn()
The method tries to do too much, which makes it hard to test. You should avoid making the services too fat and models too thin. Extract some parts to make it more manageable. E.g. if some functionality is in the models you can use it in the test instead of having it unpredictable.

2022-03-29 11:45 UTC, yCobanoglu commented on ebl/fragmentarium/application/annotations_service.py
> +        )[0]
@jlaasonen can you be more specific like a method in annotation which does what `BoundingBox.from_annotation` is doing ?

2022-03-29 13:30 UTC, yCobanoglu commented on ebl/tests/fragmentarium/test_annotations_service.py
> +    when(annotations_repository).create_or_update(...).thenReturn()
mocked the parts out but hat to set `attrs.freeze` to `False` to stub out the methods in the tests.

2022-03-30 07:19 UTC, jlaasonen commented on ebl/tests/fragmentarium/test_annotations_service.py
> +    when(annotations_repository).create_or_update(...).thenReturn()
Now you are mocking the internals of the system under test. I.e. you are testing your mock and not the actual implementation. You should mock only things outside the system under test and test them independently. Then here you would test that the service calls them correctly.

2022-03-30 20:03 UTC, yCobanoglu commented on ebl/tests/fragmentarium/test_annotations_service.py
> +    when(annotations_repository).create_or_update(...).thenReturn()
ok i improved it

2022-03-30 20:28 UTC, merged