unify fragmentarium search
ElectronicBabylonianLiterature/ebl-api pull request #230
Opened 2022-04-18 12:28 UTC by yCobanoglu

2022-04-22 06:50 UTC, jlaasonen requested changes

2022-04-22 06:50 UTC, jlaasonen commented on ebl/fragmentarium/application/fragment_finder.py
> +        if not transliteration or transliteration.is_empty():
Would it make sense to use empty `TransliterationQuery` as a [null object](https://en.wikipedia.org/wiki/Null_object_pattern) instead of using `Optional`?

2022-04-22 06:50 UTC, jlaasonen commented on ebl/fragmentarium/infrastructure/mongo_fragment_repository.py
> +        id_query: Dict[str, Dict] = dict()
Replace dict() with {} ([dict-literal](https://docs.sourcery.ai/refactorings/dict-literal/)).

2022-04-22 06:50 UTC, jlaasonen commented on ebl/fragmentarium/infrastructure/mongo_fragment_repository.py
> +    def query_fragmentarium_create_query(
☝️

2022-04-22 06:50 UTC, jlaasonen commented on ebl/fragmentarium/web/fragment_search.py
> +                raise DataError("Name, Year or Title required")
What has `id` to do with Name, Year or Title?

2022-04-25 19:10 UTC, yCobanoglu commented on ebl/fragmentarium/application/fragment_finder.py
> +        if not transliteration or transliteration.is_empty():
Kind of i did get rid of None check but because it's not possible to pass object as default value for a function (flake8) complained i have to manually instantiate it for the tests.

2022-04-25 19:20 UTC, yCobanoglu commented on ebl/fragmentarium/web/fragment_search.py
> +                raise DataError("Name, Year or Title required")
i can change it for function calls but not url possibly ?

2022-04-26 09:00 UTC, yCobanoglu commented on ebl/fragmentarium/application/fragment_finder.py
> +        if not transliteration or transliteration.is_empty():
query object

2022-04-26 09:03 UTC, yCobanoglu commented on ebl/fragmentarium/web/fragment_search.py
> +                raise DataError("Name, Year or Title required")
also frontend

2022-04-28 11:02 UTC, merged