Fragmentarium lemma search
ElectronicBabylonianLiterature/ebl-api pull request #314
Opened 2022-11-04 14:33 UTC by fsimonjetz

2022-11-11 12:16 UTC, yCobanoglu commented on ebl/fragmentarium/web/fragments.py
> +        fragment, has_photo = self._finder.find(
`req.params.get("lines", [])` so you don't have to check for `None` in the list comprehension.
For User input you have to validate that `int(i)` doesn't throw an error by `validating the params first. Catching the error and throwing a custom error ("Lines have to be numbers"). That has been done in some other place in the api.

2022-11-11 12:26 UTC, yCobanoglu commented on ebl/fragmentarium/infrastructure/mongo_fragment_repository.py
> +                *filter_fragment_lines(lines),
`lines and *filter_fragment_lines(lines)` works if `line is an empty list`

2022-11-11 12:27 UTC, yCobanoglu commented on ebl/fragmentarium/infrastructure/mongo_fragment_repository.py
> +            {
it should be enough to return an item no need for list here i think. So `{...} `instead `[{...}]`.

2022-11-11 12:31 UTC, yCobanoglu commented on ebl/fragmentarium/infrastructure/mongo_annotations_repository.py
>          try:
lines is not used why is it needed as parameter ?

2022-11-11 12:33 UTC, yCobanoglu commented on ebl/tests/fragmentarium/test_fragment_finder.py
> +    (
`query_by_museum_number(number, lines) `needs a test

2022-11-11 12:36 UTC, yCobanoglu commented on ebl/common/query/query_result.py
> +    lemma_sequences: Sequence[LemmaLine] = attr.ib(default=tuple())
Type should be tuple. Also `Tuple[LemmaLine] = tuple()`.

2022-11-11 12:36 UTC, yCobanoglu commented on ebl/common/query/query_result.py
> +    total_matching_lines: int
Also `Tuple`

2022-11-11 12:37 UTC, yCobanoglu commented on ebl/common/query/query_result.py
> +    lemma_sequences: Sequence[LemmaLine] = attr.ib(default=tuple())
what is the use of `total` maybe a more descriptive name like `total_`?

2022-11-11 12:44 UTC, yCobanoglu commented on ebl/fragmentarium/web/fragments.py
> +        fragment, has_photo = self._finder.find(
Also need a test which tests "lines".

2022-11-11 12:54 UTC, yCobanoglu commented on ebl/fragmentarium/infrastructure/phrase_matcher.py
> +            print(">>> doesn't match")
Do you want to print this on the server logs ?

2022-11-11 12:55 UTC, yCobanoglu commented on ebl/fragmentarium/web/fragments.py
> +        resp.media = QueryResultSchema().dump(self._repository.query_lemmas(req.params))
From what i understand req.params is supposed to be a dict with a single key and single value. Then it would be better to parse and validate it and pass to strings to `query_lemmas`.

2022-11-11 13:20 UTC, yCobanoglu requested changes

2022-11-11 13:20 UTC, yCobanoglu commented on ebl/fragmentarium/infrastructure/mongo_fragment_repository.py
> +        if data := next(data, {}):
```python
        if next(data, None):
            if query_operator == QueryType.PHRASE:
                filtered_data = filter_query_results(data, lemmas)
                return QueryResultSchema().load(filtered_data)
        else:
            return QueryResult([], 0)
```

2022-11-11 13:20 UTC, yCobanoglu commented on ebl/fragmentarium/infrastructure/mongo_fragment_repository.py
> +        if data := next(data, {}):
If i understand this correclty you are assigning data to {} which leads it to jump to the else branch but in the else branch you are not using data so there is no point in using the walrus operator.

2022-11-11 13:20 UTC, yCobanoglu commented on ebl/fragmentarium/infrastructure/mongo_fragment_repository.py
> +                *filter_fragment_lines(lines),
`lines and *filter_fragment_lines(lines)` works (even if line is an empty list)

2022-11-11 13:20 UTC, yCobanoglu commented on ebl/fragmentarium/infrastructure/mongo_fragment_repository.py
> +        [
it should be enough to return an item no need for list here i think. So `{...} `instead `[{...}]`.

2022-11-11 13:20 UTC, yCobanoglu commented on ebl/fragmentarium/infrastructure/mongo_annotations_repository.py
> +    ) -> Annotations:
lines is not used why is it needed as parameter ?

2022-11-11 13:20 UTC, yCobanoglu commented on ebl/common/query/query_result.py
> +    lemma_sequences: Sequence[LemmaLine] = attr.ib(default=tuple())
Tuple would be better. Also `Tuple[LemmaLine] = tuple()`. Same with matching_lines.

2022-11-11 13:20 UTC, yCobanoglu commented on ebl/common/query/query_result.py
> +    total: int
what is the use of `total` maybe a more descriptive name like `total_`?

2022-11-11 13:20 UTC, yCobanoglu commented on ebl/common/query/query_result.py
> +    items: Sequence[QueryItem]
Type Tuple should work here too

2022-11-11 13:20 UTC, yCobanoglu commented on ebl/fragmentarium/infrastructure/phrase_matcher.py
> +                print(">>> matches")
Probably you forgot to delete this debug information.

2022-11-11 13:20 UTC, yCobanoglu commented on ebl/fragmentarium/infrastructure/phrase_matcher.py
> +        return False
Same here

2022-11-11 13:20 UTC, yCobanoglu commented on ebl/fragmentarium/web/fragments.py
> +        lines: Union[Sequence[str], None] = req.params.get("lines")
`req.params.get("lines", [])` so you don't have to check for `None` and just have one type. And later you would have to check if the list is empty.
For User input you have to validate that `int(i)` doesn't throw an error by validating the params first. Catching the error and throwing a custom error ("Lines have to be numbers"). Something similar has been done in the api for reference.

2022-11-11 13:20 UTC, yCobanoglu commented on ebl/fragmentarium/web/fragments.py
> +        fragment, has_photo = self._finder.find(
Also need a test which tests "lines". A test in routes.

2022-11-11 13:20 UTC, yCobanoglu commented on ebl/fragmentarium/web/fragments.py
> +        resp.media = QueryResultSchema().dump(self._repository.query_lemmas(req.params))
From what i understand req.params is supposed to be a dict with a single key and single value. Then it would be better to parse and validate it and pass to strings to `query_lemmas`.

2022-11-11 14:59 UTC, fsimonjetz commented on ebl/fragmentarium/infrastructure/mongo_fragment_repository.py
> +                *filter_fragment_lines(lines),
Not sure if I'm following - can you specify what you mean?

2022-11-11 16:05 UTC, fsimonjetz commented on ebl/common/query/query_result.py
> +    lemma_sequences: Sequence[LemmaLine] = attr.ib(default=tuple())
> Tuple would be better

I disagree: Tuples are for fixed-length, possibly heterogeneously typed sequences of elements. Here we have homogeneously typed sequences of varying length -> that's conceptually a list. For that we use `Sequence` type in the code base and cast into `tuple` for immutability.

2022-11-11 16:09 UTC, fsimonjetz commented on ebl/common/query/query_result.py
> +    total: int
It's basically `len(matching_lines)`, I'll rename it

2022-11-11 16:12 UTC, fsimonjetz commented on ebl/fragmentarium/web/fragments.py
> +        lines: Union[Sequence[str], None] = req.params.get("lines")
`None` -> "don't filter"/return all lines
`[]` -> "return no lines".

I.e., `None != []`

2022-11-11 16:23 UTC, fsimonjetz commented on ebl/fragmentarium/web/fragments.py
> +        lines: Union[Sequence[str], None] = req.params.get("lines")
In principle you're right, but this is not for user input. But if we want to use this for user input at some point, we should add validation!

2022-11-11 16:26 UTC, fsimonjetz commented on ebl/fragmentarium/web/fragments.py
> +        resp.media = QueryResultSchema().dump(self._repository.query_lemmas(req.params))
You're right, I changed it. We will soon want to add additional filters, but handling them separate from the main query is probably a good idea.

2022-11-11 18:38 UTC, yCobanoglu commented on ebl/fragmentarium/web/fragments.py
> +        lines: Union[Sequence[str], None] = req.params.get("lines")
Api calls in principle should still be validated users could theoretically still call this api even if there is no frontend interface for it.

2022-11-11 18:45 UTC, yCobanoglu commented on ebl/fragmentarium/infrastructure/mongo_fragment_repository.py
> +                *filter_fragment_lines(lines),
This makes only sense if `None` and `[]` represent the same but like you said empty list has a meaning it makes no sense. Otherwise `lines and *filter_fragment_lines` return either `lines` if `lines` is not empty or None or if its empty or None it return `filter_fragment_lines(lines)`.

2022-11-14 15:04 UTC, fsimonjetz commented on ebl/fragmentarium/infrastructure/mongo_fragment_repository.py
> +                *filter_fragment_lines(lines),
Thanks for clarifying, I understand! (But it's the other way around, no? `lines` would be returned if it *is* empty or `None`, otherwise the filter gets called.) Either way, as you said it'd be a good solution if `None == []`. Do you think it would make sense to create a [sentinel value](https://death.andgravity.com/sentinels) for `None` to make it more obvious that it has a meaning to it?

2022-11-15 12:01 UTC, yCobanoglu approved these changes

2022-11-18 10:28 UTC, merged