Select genre
ElectronicBabylonianLiterature/ebl-api pull request #43
Opened 2020-08-21 22:13 UTC by yCobanoglu

2020-08-26 13:18 UTC, jlaasonen commented
![](https://github.trello.services/images/mini-trello-icon.png) [Select Genre in Fragmentarium](https://trello.com/c/ps6PD12L/331-select-genre-in-fragmentarium)

2020-09-04 07:17 UTC, jlaasonen requested changes
You say that the genre is a tree structure, but here it is a nested list of strings. There should be validation that the genres are correct. Now it would be possible to set e.g. to [["foo", "bar"]]. 

If the genre is defined by a tree, saving  the parent information in the fragment seems redundant. Also, changing the tree would require updating all the fragments.

2020-09-04 07:17 UTC, jlaasonen commented on ebl/fragmentarium/web/fragment_genre.py
> +import falcon  # pyre-ignore
Please ignore a specific error.

2020-09-04 09:23 UTC, yCobanoglu commented
> You say that the genre is a tree structure, but here it is a nested sequence of strings. There should be validation that the genres are correct. Now it would be possible to set e.g. to `[["foo", "bar"]]`.
> 
> If the genre is defined by a tree, saving the parent information in the fragment seems redundant. Also, changing the tree would require updating all the fragments.

@jlaasonen 
I can make a validation. But saving only the **leaf** of the trees in the database, how could one search for the **nodes** of that **leaf** in the database ?

2020-09-04 10:12 UTC, jlaasonen commented
> > You say that the genre is a tree structure, but here it is a nested sequence of strings. There should be validation that the genres are correct. Now it would be possible to set e.g. to `[["foo", "bar"]]`.
> > If the genre is defined by a tree, saving the parent information in the fragment seems redundant. Also, changing the tree would require updating all the fragments.
> 
> @jlaasonen
> I can make a validation. But saving only the **leaf** of the trees in the database, how could one search for the **nodes** of that **leaf** in the database ?

Is there a requirement to search **leaves** or **nodes**? What we have now is just a bunch of strings there is are no **leaves** and **nodes**. If we need to search **genres** the query can be constructed from the genre configuration. You can keep the denormalized format if you think it is better, but you must ensure that it is correct all the time.

2020-09-04 10:14 UTC, jlaasonen commented
About modelling trees in mongo: https://docs.mongodb.com/manual/applications/data-models-tree-structures/

2020-09-11 07:34 UTC, jlaasonen requested changes

2020-09-11 07:34 UTC, jlaasonen commented on ebl/fragmentarium/web/bootstrap.py
> +    api.add_route("/genre", genre)
Resource name should `genres`.

2020-09-11 07:34 UTC, jlaasonen commented on ebl/fragmentarium/web/fragment_genre.py
> +        return all(genre in genres for genre in genres_retrieved)
The validation should be in the fragment model.

2020-09-11 07:34 UTC, jlaasonen commented on ebl/fragmentarium/web/fragment_genre.py
> +            }
If you raise a `DataError` the error handler will take care of the response.

2020-09-11 07:34 UTC, jlaasonen commented on ebl/tests/fragmentarium/test_fragment.py
> +    assert fragment.genre == genre
This is redundant. Getting the genre is already tested above.

2020-09-11 07:34 UTC, jlaasonen commented on ebl/tests/fragmentarium/test_fragment.py
> +def test_set_genre():
Put this together with the other genre tests.

2020-09-11 07:34 UTC, jlaasonen commented on ebl/tests/fragmentarium/test_fragment_repository.py
> +        parse_museum_number(fragment_number)
Use `fragment.number` instead of parsing the `_id`.

2020-09-11 07:34 UTC, jlaasonen commented on ebl/fragmentarium/domain/genre.py
> +genres = [
Shouldn't there be more genres?

2020-09-11 07:51 UTC, jlaasonen requested changes

2020-09-11 07:51 UTC, jlaasonen commented on ebl/fragmentarium/domain/fragment.py
> +        return attr.evolve(self, genre=tuple(map(tuple, genre)))  # pyre-ignore[6]
Pyre errors should not be arbitrarily ignored. In general, only errors from libraries without types should be ignored.

Mypy had an option to treat them as `Any`, but pyre likes to complain about them whenever possible.

2020-09-11 07:51 UTC, jlaasonen commented on ebl/fragmentarium/domain/genre.py
> +genres = [
Genres should be `tuple`s to avoid accidental modification.

2020-09-14 11:36 UTC, yCobanoglu commented on ebl/fragmentarium/domain/fragment.py
> +        return attr.evolve(self, genre=tuple(map(tuple, genre)))  # pyre-ignore[6]
i cercumvented this error py creating a new function and adding this link as a comment.
[https://github.com/python/mypy/issues/1317](url)
weirdly enough `list(map(list, genre))` works (that is used in **test_genre_route.py**.

2020-09-14 12:52 UTC, jlaasonen commented on ebl/fragmentarium/domain/fragment.py
> +# https://github.com/python/mypy/issues/1317
Mypy does not work with Pypy. Does this also affect Pyre?

2020-09-14 12:56 UTC, jlaasonen requested changes

2020-09-14 12:56 UTC, jlaasonen commented on ebl/fragmentarium/domain/fragment.py
> +            raise ValueError(f"'{(genre_retrieved)}' is not a valid genre")
You could use [validator](https://www.attrs.org/en/stable/examples.html?highlight=validator#validators). Now it is possible to set incorrect genres during init.

2020-09-14 13:23 UTC, yCobanoglu commented on ebl/fragmentarium/domain/fragment.py
> +# https://github.com/python/mypy/issues/1317
i changed it to **List comprehenion**. I couldnt find anything concerning this issue for **pyre**.
Also we have the same code (namely: `tuple(map(tuple, ...)`in **fragment_info_schema.py** and a similar line with `list`instead of `tuple`in **test_genre_route.py**. No clue whats the issue with **pyre**.

2020-09-14 14:10 UTC, yCobanoglu commented on ebl/fragmentarium/domain/fragment.py
> +            raise ValueError(f"'{(genre_retrieved)}' is not a valid genre")
oh yeah could call would have totally missed that **!**

2020-09-14 14:29 UTC, yCobanoglu commented on ebl/fragmentarium/domain/fragment.py
> +            raise ValueError(f"'{(genre_retrieved)}' is not a valid genre")
So whats weird is that the validator takes a genre argument in initialzation which is `Tuple[Tuple[str,...],...]` but you can pass it a `list` and it wont throw a `TypeError`.

2020-09-15 06:32 UTC, jlaasonen commented on ebl/fragmentarium/domain/fragment.py
> +        self._check_is_genre_valid(None, genre_retrieved)
This should not be necessary. See: https://www.attrs.org/en/stable/api.html?highlight=evolve#attr.evolve

2020-09-15 06:33 UTC, jlaasonen approved these changes

2020-09-16 10:18 UTC, yCobanoglu commented on ebl/fragmentarium/domain/fragment.py
> +        self._check_is_genre_valid(None, genre_retrieved)
ok

2020-09-16 22:58 UTC, yCobanoglu commented
unfortunatley i got the genre "data" model wrong every genre needs a property uncertain which can be true or false. After reading the trello card today it became clear to me it was my fault but anyways the backend is ready a genre is now a class.

2020-09-18 09:05 UTC, jlaasonen commented on ebl/fragmentarium/domain/fragment.py
> +            raise ValueError(f"'{(genre_retrieved)}' is not a valid genre")
Types are not checked runtime.

2020-09-18 10:38 UTC, jlaasonen approved these changes

2020-09-24 15:09 UTC, merged