mongosync script
ElectronicBabylonianLiterature/ebl-api pull request #53
Opened 2020-10-05 13:07 UTC by yCobanoglu

2020-10-22 01:26 UTC, yCobanoglu commented
@jlaasonen everything is working **besides** environment variables. They aren't passed to the container/ the script. If i hardcode the env variables in the mongosync.sh  it works but if i try to access then through docker-compose it fails.

2020-10-22 11:46 UTC, jlaasonen requested changes
You removed the old script, but the new one does not have all the feature. E.g. allow any DB or use different host and user for source and target.

Either implement the missing features and update the README or move the script to own repository.

2020-10-22 11:46 UTC, jlaasonen commented on mongosync/mongosync.sh
> +printenv
The environment contains secrets. Do not print it.

2020-10-22 12:10 UTC, jlaasonen commented
![](https://github.trello.services/images/mini-trello-icon.png) [Synching Ebl-dev database with bash script](https://trello.com/c/eUptlA9M/470-synching-ebl-dev-database-with-bash-script)

2020-10-23 08:57 UTC, jlaasonen commented
Moved to own repository: https://github.com/ElectronicBabylonianLiterature/mongosync

2020-10-23 08:57 UTC, closed without merging