Line to vec
ElectronicBabylonianLiterature/ebl-api pull request #60
Opened 2020-10-26 17:26 UTC by yCobanoglu

2020-11-27 09:38 UTC, jlaasonen commented
![](https://github.trello.services/images/mini-trello-icon.png) [Count number of rulings in tablet to find matching sequences](https://trello.com/c/GRpAtWIj/47-count-number-of-rulings-in-tablet-to-find-matching-sequences)

2020-12-07 11:36 UTC, yCobanoglu commented
![](https://github.trello.services/images/mini-trello-icon.png) [Count number of rulings in tablet to find matching sequences](https://trello.com/c/GRpAtWIj/47-count-number-of-rulings-in-tablet-to-find-matching-sequences)

2020-12-07 13:00 UTC, jlaasonen requested changes

2020-12-07 17:41 UTC, yCobanoglu commented on ebl/fragmentarium/application/create_line_to_vec.py
> +        return tuple(map(LineToVecEncoding, sequence))
ok do you have a suggestion where to put it ? I could make it a function (not part of an object) and leave it in **create_line_to_vec**

2020-12-07 17:42 UTC, yCobanoglu commented on ebl/fragmentarium/domain/fragment.py
> +        return attr.evolve(self, line_to_vec=line_to_vec)
i delete this function there is no need for it everything is done in update_transliteration

2020-12-08 09:19 UTC, yCobanoglu commented on ebl/fragmentarium/application/create_line_to_vec.py
> +        or line.line_number.prefix_modifier  # pyre-ignore[16]
Will be fixed soon !

2020-12-09 12:12 UTC, jlaasonen commented on ebl/fragmentarium/application/create_line_to_vec.py
> +        return tuple(map(LineToVecEncoding, sequence))
It is used for deserialization so using a schema could be better. Otherwise, put it (next) to the repository. The use in `create_line_to_vec` seems obsolete.

2020-12-09 12:56 UTC, jlaasonen commented on ebl/fragmentarium/infrastructure/fragment_repository.py
> +            ): tuple(
Are you using museum numbers of fragment IDs? The string representation of the museum number is not necessarily the same as the ID.

If you need the ID you should us `_id`. If you need the museum number there should be no need to convert to string.

2020-12-09 13:04 UTC, jlaasonen commented on ebl/fragmentarium/update_fragments.py
> +    states = Parallel(n_jobs=number_of_jobs, backend="multiprocessing")(
Why use the old backend?

2020-12-09 13:04 UTC, jlaasonen commented on ebl/fragmentarium/update_fragments.py
> +    number_of_jobs = 16
Maybe this should be taken from the environment (with a reasonable default) instead of committing a value which fits your machine.

2020-12-09 13:08 UTC, jlaasonen requested changes

2020-12-09 13:08 UTC, jlaasonen commented on ebl/fragmentarium/domain/fragment.py
> +)
The *domain* must not depend on the *application*.

2020-12-09 13:08 UTC, jlaasonen commented on ebl/fragmentarium/web/fragment_matcher.py
> +                number = tuple([int(x.strip()) for x in number])
This looks like a leftover from a previous implementation. Please, remove it a and the related code in fragment matcher.

2020-12-11 13:04 UTC, yCobanoglu commented on ebl/fragmentarium/update_fragments.py
> +    states = Parallel(n_jobs=number_of_jobs, backend="multiprocessing")(
I wanted to use something else then threads i think.

2020-12-11 13:05 UTC, yCobanoglu commented on ebl/fragmentarium/update_fragments.py
> +    number_of_jobs = 16
we could pass it as command line argument ? Would better than env or what do you think ?

2020-12-11 13:07 UTC, yCobanoglu commented on ebl/fragmentarium/web/fragment_matcher.py
> +                number = tuple([int(x.strip()) for x in number])
This would allow user to define specific sequences like this: **fragmentarium/[1,2,2,3,5]/match**
Could be useful for Tonia what should i do ?

2020-12-11 13:20 UTC, yCobanoglu commented on ebl/fragmentarium/domain/fragment.py
> +)
it s in its own file now didnt work in fragments.py because of a circular dependeny (creeate_line_to_vec)

2020-12-11 13:20 UTC, yCobanoglu commented on ebl/fragmentarium/update_fragments.py
> +    number_of_jobs = 16
make it after merging

2020-12-11 13:25 UTC, jlaasonen commented on ebl/fragmentarium/web/fragment_matcher.py
> +                number = tuple([int(x.strip()) for x in number])
Ask him if it would be useful. If it is useful there should be a proper UI not a hack on an existing route.

The rulings encoding is not a resource id and should go to the query string like other searches: `fragments?rulings=[1,2,2,3,5]`. 

Getting the rulings for the fragment ID should be done as early as possible to avoid having to use `isinstacene` in the line to vec implementation.

2020-12-11 13:26 UTC, jlaasonen commented on ebl/fragmentarium/update_fragments.py
> +    number_of_jobs = 16
Command line argument would be good.

2020-12-11 13:31 UTC, jlaasonen commented on ebl/fragmentarium/update_fragments.py
> +    states = Parallel(n_jobs=number_of_jobs, backend="multiprocessing")(
Just use the default unless there is a reason not to.

See: 
https://joblib.readthedocs.io/en/latest/parallel.html#thread-based-parallelism-vs-process-based-parallelism
https://joblib.readthedocs.io/en/latest/parallel.html#old-multiprocessing-backend

2020-12-14 08:19 UTC, yCobanoglu commented on ebl/fragmentarium/web/fragment_matcher.py
> +                number = tuple([int(x.strip()) for x in number])
ok then i am going to get rid of it now and ask him once we merged.

2020-12-14 10:23 UTC, jlaasonen approved these changes

2020-12-14 10:50 UTC, merged